### PR TITLE
fix: segfault on neovim nightly

### PR DESCRIPTION
**Pull request by krivahtoo**
#18 #10

### CODE REVIEW

**Comment by ls-devs** [comment]
@krivahtoo Still get the error : 

Screenshot from 2022-12-19 08-25-32


```
NVIM v0.9.0-dev-525+ga7332ba9b
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

```

**Comment by krivahtoo** [comment]
@ls-devs I cannot reproduce this. can you share your config?

**Comment by ls-devs** [comment]
silicon.lua 
```
require("silicon").setup({
	font = "Fira Code Font=16",
})
```

installed via packer : 
```
use({ "krivahtoo/silicon.nvim", run = "./install.sh" })
```

Neovim version : 
```
NVIM v0.9.0-dev-525+ga7332ba9b
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/laurent/Utils/neovim/build/cmake.config -I/home/laurent/Utils/neovim/src -I/home/laurent/Utils/neovim/.deps/usr/include -I/usr/include -I/home/laurent/Utils/neovim/build/src/nvim/auto -I/home/laurent/Utils/neovim/build/include
```

OS : 

```
            .-/+oossssoo+/-.               laurent@laurent 
        `:+ssssssssssssssssss+:`           --------------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 22.04.1 LTS x86_64 
    .ossssssssssssssssssdMMMNysssso.       Host: NL40_50CU 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 5.15.0-56-generic 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 6 hours, 22 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 2682 (dpkg), 20 (snap) 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: zsh 5.8.1 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 1920x1080 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   DE: GNOME 42.5 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: Mutter 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   WM Theme: Sweet-mars-v40 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Theme: Sweet-Mars [GTK2/3] 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Icons: SweetMars [GTK2/3] 
  +sssssssssdmydMMMMMMMMddddyssssssss+     Terminal: gnome-terminal 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      CPU: Intel i7-10510U (8) @ 4.900GHz 
    .ossssssssssssssssssdMMMNysssso.       GPU: Intel CometLake-U GT2 [UHD Graphics] 
      -+sssssssssssssssssyyyssss+-         Memory: 2250MiB / 15244MiB 
        `:+ssssssssssssssssss+:`
            .-/+oossssoo+/-.                                       
                                                                   
```

See : 
image

**Comment by krivahtoo** [comment]
You are using the pre-build release which does not contain this merge.

If you have `cargo` you could use `use({ "krivahtoo/silicon.nvim", run = "./install.sh build" })` or run `./install.sh build` on plugin install path.

**Comment by ls-devs** [comment]
> If you have `cargo` you could use `use({ "krivahtoo/silicon.nvim", run = "./install.sh build" })` or run `./install.sh build` on plugin install path.

I can confirm it's working after `./install.sh build`.
Thanks ! 👍🏼

**Pull request merged**
